[package]
name = "teamcal"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", features = [ "serde" ] }
askama = "0.10.5"
serde = { version = "1.0.132", features = [ "derive" ] }
serde_json = "1.0.73"
structopt = "0.3.25"